// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_5a0HUj_K1p_BfMZUaWEnn8p07dBEXV0',
    appId: '1:255181237348:android:9017ef5aa94650b72ec371',
    messagingSenderId: '255181237348',
    projectId: 'nsu-new-2076a',
    storageBucket: 'nsu-new-2076a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjAFnvagiGkosDjVJVWTW1oAN1cO9QCQY',
    appId: '1:255181237348:ios:831f186ab2a230b62ec371',
    messagingSenderId: '255181237348',
    projectId: 'nsu-new-2076a',
    storageBucket: 'nsu-new-2076a.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD18RhWthjQ8ChqNNP4vFN4dNkHvNpCF3Q',
    appId: '1:255181237348:web:63445dc37f152a5a2ec371',
    messagingSenderId: '255181237348',
    projectId: 'nsu-new-2076a',
    authDomain: 'nsu-new-2076a.firebaseapp.com',
    storageBucket: 'nsu-new-2076a.appspot.com',
    measurementId: 'G-Y8JXCRJ4ZY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjAFnvagiGkosDjVJVWTW1oAN1cO9QCQY',
    appId: '1:255181237348:ios:831f186ab2a230b62ec371',
    messagingSenderId: '255181237348',
    projectId: 'nsu-new-2076a',
    storageBucket: 'nsu-new-2076a.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD18RhWthjQ8ChqNNP4vFN4dNkHvNpCF3Q',
    appId: '1:255181237348:web:f1520b1bcdae79122ec371',
    messagingSenderId: '255181237348',
    projectId: 'nsu-new-2076a',
    authDomain: 'nsu-new-2076a.firebaseapp.com',
    storageBucket: 'nsu-new-2076a.appspot.com',
    measurementId: 'G-FV86B1H147',
  );

}